name: Release

on:
  push:
    tags:
      - '[0-9]*.[0-9]*.[0-9]*'

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
      - uses: actions/setup-node@60edb5dd545a775178f52524783378180af0d1f8 # v4.0.2
        with:
          node-version: lts/*
          cache: npm
      - run: npm ci
      - run: npm run verify
      - name: Ensure styles.css exists
        run: test -f styles.css || touch styles.css
      - uses: softprops/action-gh-release@3bb12739c298aeb8a4eeaf626c5b8d85266b0e65 # v2.6.2
        with:
          files: |
            main.js
            manifest.json
            styles.css
